### ISSUE TITLE
Add Styles.

### ISSUE THREAD

**Issue by farhanlatif-coder** [lakhaniji/Tourism-Website#1]

**Comment by devWonderkind** [comment]
hey @lakhaniji i'm intrested work on this issue can you assign me?

**Comment by sambit7701** [comment]
hey @lakhaniji I'm also in interested to work on this issue can you assign me?

**Comment by farhanlatif-coder** [comment]
Yeah, you both can give a try

**Comment by farhanlatif-coder** [comment]
Good work @sambit7701
